import type { Metadata } from 'next';
import './globals.css';
import Navbar from '../components/Navbar';

export const metadata: Metadata = {
  title: 'The AI Interview Prep Kit | PrepKit AI',
  description: 'Turn any job description and company URL into a comprehensive, personalised interview preparation kit — with deterministic question coverage, scheduling, and flashcards.',
  keywords: 'interview prep, AI interview kit, job description, LeetCode, system design, behavioral, coding interview',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className="min-h-screen flex flex-col antialiased bg-[#040605] text-[#f1f5f4]"
      >
        <Navbar />
        <main className="flex-1 relative z-10 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {children}
        </main>

        {/* Footer */}
        <footer className="relative z-10 py-6 border-t border-[#1b2720]/60">
          <div className="max-w-7xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-2 text-slate-500 text-xs">
            <span>© 2025 PrepKit AI · Powered by Gemini</span>
            <span>
              All kits generated by a{' '}
              <span className="text-emerald-400 font-semibold">deterministic pipeline</span>
              {' '}— not a single prompt.
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
